main: com.psiloclast.buttplugmc.ButtplugMc
name: ButtplugMc
version: 0.0.1
author: Psiloclast
description: Control your sex toys from within Minecraft
api-version: 1.17
commands:
  vibrate:
    description: Manually set your toy's level (level must be between 0 and 100)
    usage: /vibrate <level>
